apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-key-rotation-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-key-rotation-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-key-rotation-binding-secret
subjects:
  - kind: ServiceAccount
    name: aws-key-rotation-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: aws-key-rotation-clusterrole
  apiGroup: rbac.authorization.k8s.io
